services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.local
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src/
        target: /var/www/html
    restart: always

  app:
    container_name: app
    env_file:
      - ./src/.env.local
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /var/www/html
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb:latest
    ports:
      - 3306:3306
    env_file:
      - ./docker/db/.env.local
    volumes:
      - type: bind
        source: C:/Docker/Volume/learning-php-laravel/MariaDB/
        target: /var/lib/mysql
    restart: always

  admin:
    container_name: admin
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - db

