services:
  app:
    container_name: app
    env_file:
      - ./src/.env.production
    build:
      context: .
      dockerfile: ./container/app/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    restart: always
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./container/node/Dockerfile
    ports:
      - 5173:5173
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    working_dir: /workspace
    depends_on:
      - app
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./container/web/Dockerfile.production
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    ports:
      - 1080:80
    restart: always
    depends_on:
      - app
      