services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /var/www/html
    ports:
      - 9080:80
    restart: always
  app:
    container_name: app
    env_file:
      - ./src/.env.production
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /var/www/html
    restart: always
    depends_on:
      - db
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 5173:5173
    tty: true
    volumes:
      - type: bind
        source: ./src/
        target: /workspace
    working_dir: /workspace
  db:
    container_name: db
    image: mariadb:latest
    env_file:
      - ./docker/db/.env.production
    restart: always
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    ports:
      - 3306:3306
  admin:
    container_name: admin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
volumes:
  mariadb:
