services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - type: bind
        source: .\src\
        target: /var/www/html
    ports:
      - 80:80
    restart: always
  app:
    container_name: app
    env_file:
      - ./src/.env
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: .\src\
        target: /var/www/html
    restart: always
    depends_on:
      - db
  # node:
  #   container_name: node
  #   build:
  #     context: .
  #     dockerfile: ./docker/node/Dockerfile
  #   ports:
  #     - 5173:5173
  #   tty: true
  #   volumes:
  #     - type: bind
  #       source: ./src/
  #       target: /workspace
  #   working_dir: /workspace
  db:
    container_name: db
    image: mariadb:latest
    restart: always
    volumes:
      - type: bind
        source: C:\Docker\Volume\learning-php-laravel\MariaDB\
        target: /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=ipenw023
      - MARIADB_DATABASE=ec_site
      - MARIADB_USER=ec_admin
      - MARIADB_PASSWORD=ipenw023
      - "TZ=Asia/Tokyo"
  admin:
    container_name: admin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
