services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /var/www/html
    ports:
      - 9080:80
    restart: always
    depends_on:
      - app
  app:
    container_name: app
    env_file:
      - ./src/.env.production
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /var/www/html
    restart: always
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 5173:5173
    tty: true
    volumes:
      - type: bind
        source: ./src/
        target: /workspace
    working_dir: /workspace
    depends_on:
      - app