services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /var/www/html
    ports:
      - 10080:80
    restart: always
  app:
    container_name: app
    env_file:
      - ./src/.env
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /var/www/html
    restart: always
    depends_on:
      - db
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 5173:5173
    tty: true
    volumes:
      - type: bind
        source: ./src/
        target: /workspace
    working_dir: /workspace
  db:
    container_name: db
    image: mariadb:latest
    restart: always
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=iM6uj8Tu9g8KE9T5
      - MARIADB_DATABASE=ec_site
      - MARIADB_USER=ec_admin
      - MARIADB_PASSWORD=iM6uj8Tu9g8KE9T5
      - "TZ=Asia/Tokyo"
  admin:
    container_name: admin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
  mailserver:
    container_name: mail
    env_file:
      - ./docker/mail/.env
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - type: volume
        source: dms_mail_data
        target: /var/mail/
      - type: volume
        source: dms_mail_state
        target: /var/mail-state/
      - type: volume
        source: dms_mail_logs
        target: /var/log/mail/
      - type: volume
        source: dms_config
        target: /tmp/docker-mailserver/
      - type: volume
        source: dms_certs
        target: /opt/dms/certs/
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
volumes:
  mariadb:
  dms_mail_data:
  dms_mail_state:
  dms_mail_logs:
  dms_config:
  dms_certs:
  